# Copyright (C) 2024 Andrea Raffo <andrea.raffo@ibv.uio.no>
#
# SPDX-License-Identifier: MIT

name: 2024-stripepy-paper
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - bioframe=0.7
  - h5py>=3,<4
  - hictkpy=1.1.0
  - matplotlib=3.8
  - numpy=1.26
  - pandas=2.2
  - scikit-learn=1.5
  - seaborn=0.13
  - stripepy-hic=0.0.2
