# Copyright (c) 2025 Roberto Rossini (roberros@uio.no)
#
# SPDX-License-Identifier: MIT

name: Build Dockerfile

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  build-dockerfile:
    name: Build Dockerfile for ${{ inputs.name }} v${{ inputs.version}}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate tags
        id: generate-tags
        working-directory: ${{ github.workspace }}/dockerfiles
        run: |
          base_tag="ghcr.io/${{ github.repository }}/${{ inputs.name }}"

          tags="$base_tag:${{ inputs.version }}"
          tags+=",$base_tag:latest"

          echo "Tags: $tags"
          echo "tags=$tags" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # 3.10.0
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # 3.6.0
        with:
          platforms: arm64

      - name: Build Docker image and push to registries
        id: docker-build
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.generate-tags.outputs.tags }}
          file: dockerfiles/${{ inputs.name }}.Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            CONTAINER_TITLE=${{ inputs.name }}
            CONTAINER_VERSION=${{ inputs.version }}
